FROM openjdk:17-slim AS builder

WORKDIR /app

COPY . . 

RUN ./gradlew bootjar

FROM openjdk:17-slim

COPY --from=builder /app/build/libs/*.jar /app

CMD ["java", "-jar","build/libs/spring-security-security-*.jar"]